// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250705054337_Customer-seed")]
    partial class Customerseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Data.Models.Customer", b =>
                {
                    b.Property<int>("Number")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Number"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Number");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Number = 1,
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Gender = "F",
                            Name = "Alice"
                        },
                        new
                        {
                            Number = 2,
                            DateOfBirth = new DateOnly(1985, 5, 20),
                            Gender = "M",
                            Name = "Bob"
                        },
                        new
                        {
                            Number = 3,
                            DateOfBirth = new DateOnly(2000, 12, 15),
                            Gender = "M",
                            Name = "Charlie"
                        },
                        new
                        {
                            Number = 4,
                            DateOfBirth = new DateOnly(1995, 8, 10),
                            Gender = "F",
                            Name = "Diana"
                        },
                        new
                        {
                            Number = 5,
                            DateOfBirth = new DateOnly(1988, 3, 5),
                            Gender = "M",
                            Name = "Edward"
                        },
                        new
                        {
                            Number = 6,
                            DateOfBirth = new DateOnly(1992, 7, 19),
                            Gender = "F",
                            Name = "Fiona"
                        },
                        new
                        {
                            Number = 7,
                            DateOfBirth = new DateOnly(1983, 10, 23),
                            Gender = "M",
                            Name = "George"
                        },
                        new
                        {
                            Number = 8,
                            DateOfBirth = new DateOnly(1999, 11, 11),
                            Gender = "F",
                            Name = "Hannah"
                        },
                        new
                        {
                            Number = 9,
                            DateOfBirth = new DateOnly(1991, 2, 17),
                            Gender = "M",
                            Name = "Ian"
                        },
                        new
                        {
                            Number = 10,
                            DateOfBirth = new DateOnly(1996, 6, 6),
                            Gender = "F",
                            Name = "Julia"
                        },
                        new
                        {
                            Number = 11,
                            DateOfBirth = new DateOnly(1987, 4, 13),
                            Gender = "M",
                            Name = "Kevin"
                        },
                        new
                        {
                            Number = 12,
                            DateOfBirth = new DateOnly(1993, 9, 2),
                            Gender = "F",
                            Name = "Laura"
                        },
                        new
                        {
                            Number = 13,
                            DateOfBirth = new DateOnly(1989, 12, 24),
                            Gender = "M",
                            Name = "Mike"
                        },
                        new
                        {
                            Number = 14,
                            DateOfBirth = new DateOnly(1997, 1, 30),
                            Gender = "F",
                            Name = "Nina"
                        },
                        new
                        {
                            Number = 15,
                            DateOfBirth = new DateOnly(1982, 8, 18),
                            Gender = "M",
                            Name = "Oscar"
                        },
                        new
                        {
                            Number = 16,
                            DateOfBirth = new DateOnly(1994, 5, 9),
                            Gender = "F",
                            Name = "Paula"
                        },
                        new
                        {
                            Number = 17,
                            DateOfBirth = new DateOnly(1990, 10, 4),
                            Gender = "M",
                            Name = "Quentin"
                        },
                        new
                        {
                            Number = 18,
                            DateOfBirth = new DateOnly(1998, 3, 22),
                            Gender = "F",
                            Name = "Rachel"
                        },
                        new
                        {
                            Number = 19,
                            DateOfBirth = new DateOnly(1986, 6, 14),
                            Gender = "M",
                            Name = "Steve"
                        },
                        new
                        {
                            Number = 20,
                            DateOfBirth = new DateOnly(1995, 12, 1),
                            Gender = "F",
                            Name = "Tina"
                        });
                });

            modelBuilder.Entity("WebApplication1.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "password123",
                            Username = "azmarafi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
